apiVersion: v1
entries:
  buzzfeed-sso:
  - apiVersion: v1
    appVersion: 2.1.0
    created: "2020-11-05T13:28:03.391096+01:00"
    description: Single sign-on for your Kubernetes services using Google OAuth
    digest: 5436bf022d1fdf2a6a8a33673ec73e8c4e11b6bedf5e7e2dbca243ac9080e978
    home: https://github.com/buzzfeed/sso
    icon: https://user-images.githubusercontent.com/10510566/44476420-a64e5980-a605-11e8-8ad9-2820109deb75.png
    keywords:
    - sso
    - octoboi
    - ssoctopus
    maintainers:
    - email: dblanco@minddoc.de
      name: darioblanco
    - email: alen.komljen@live.com
      name: komljen
    name: buzzfeed-sso
    sources:
    - https://hub.docker.com/r/buzzfeed/sso/
    urls:
    - buzzfeed-sso-0.2.7.tgz
    version: 0.2.7
  istio-operator:
  - apiVersion: v1
    created: "2020-11-05T13:28:03.392404+01:00"
    description: Helm chart for deploying Istio operator
    digest: b5e55cce2d1cf9fef6574a7b3ae111532a36f73f9c18ab1c06b5263e0c3ea043
    icon: https://istio.io/latest/favicons/android-192x192.png
    keywords:
    - istio
    - operator
    name: istio-operator
    sources:
    - https://github.com/istio/istio/tree/master/operator
    urls:
    - istio-operator-1.7.0.tgz
    version: 1.7.0
generated: "2020-11-05T13:28:03.388083+01:00"
